name: Build and push Docker image to docker hub
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
    tags:
      - "*"
jobs:
  build-and-push:
    name: BuildAndPush
    runs-on: ubuntu-latest
    steps:
      # This step uses Github's checkout-action: https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # This step uses Docker's build-push-action: https://github.com/docker/build-push-action
      - name: Build and push Docker image to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: quortexio/deployment-tools
          tag_with_ref: true
